# Generated by Django 6.0.2 on 2026-02-07 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("menu_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=50)),
                ("item_category", models.CharField(max_length=50)),
                ("pricing_type", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "MENU_ITEM",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("table_num", models.IntegerField(default=1)),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("order_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("total_amount", models.FloatField(default=0)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "ORDER",
            },
        ),
        migrations.CreateModel(
            name="SeafoodItem",
            fields=[
                ("seafood_id", models.AutoField(primary_key=True, serialize=False)),
                ("seafood_type", models.CharField(max_length=50)),
                ("seafood_unit_price", models.FloatField(default=0)),
                ("weight_range", models.FloatField(default=0)),
            ],
            options={
                "db_table": "SEAFOOD_ITEM",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("staff_id", models.AutoField(primary_key=True, serialize=False)),
                ("staff_name", models.CharField(max_length=50)),
                ("staff_role", models.CharField(max_length=20)),
                ("staff_email", models.CharField(max_length=50)),
                ("staff_password", models.CharField(max_length=25)),
            ],
            options={
                "db_table": "STAFF",
            },
        ),
        migrations.CreateModel(
            name="FixedPricing",
            fields=[
                (
                    "menu_item",
                    models.OneToOneField(
                        db_column="menu_item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="jsquared_app.menuitem",
                    ),
                ),
                ("fixed_price", models.FloatField(default=0)),
            ],
            options={
                "db_table": "FIXED_PRICING",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("order_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_quantity", models.IntegerField(default=1)),
                ("unit_price", models.FloatField(default=0)),
                ("subtotal", models.FloatField(default=0)),
                (
                    "menu_item",
                    models.ForeignKey(
                        db_column="menu_item_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="jsquared_app.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="jsquared_app.order",
                    ),
                ),
            ],
            options={
                "db_table": "ORDER_ITEM",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="staff",
            field=models.ForeignKey(
                db_column="staff_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="jsquared_app.staff",
            ),
        ),
        migrations.CreateModel(
            name="VariedPricing",
            fields=[
                (
                    "menu_item",
                    models.OneToOneField(
                        db_column="menu_item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="jsquared_app.menuitem",
                    ),
                ),
                ("menu_price", models.FloatField(default=0)),
                (
                    "seafood",
                    models.ForeignKey(
                        db_column="seafood_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="jsquared_app.seafooditem",
                    ),
                ),
            ],
            options={
                "db_table": "VARIED_PRICING",
            },
        ),
    ]
