# Generated by Django 6.0.2 on 2026-02-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsquared_app", "0002_price_inquiry_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="staff_role",
            field=models.CharField(
                choices=[
                    ("Staff", "Staff"),
                    ("Cashier", "Cashier"),
                    ("Manager", "Manager"),
                ],
                max_length=24,
            ),
        ),
    ]
