# Generated by Django 6.0.2 on 2026-02-17 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsquared_app", "0003_alter_staff_staff_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="staff",
            field=models.ForeignKey(
                db_column="staff_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="jsquared_app.staff",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="fixed_item",
            field=models.ForeignKey(
                blank=True,
                db_column="fixed_item_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jsquared_app.fixedmenuitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="varied_item",
            field=models.ForeignKey(
                blank=True,
                db_column="varied_item_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jsquared_app.variedmenuitem",
            ),
        ),
        migrations.AlterField(
            model_name="priceinquiryrequest",
            name="meat",
            field=models.ForeignKey(
                db_column="meat_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="jsquared_app.meatitem",
            ),
        ),
        migrations.AlterField(
            model_name="priceinquiryrequest",
            name="requested_by",
            field=models.ForeignKey(
                db_column="requested_by",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_requests",
                to="jsquared_app.staff",
            ),
        ),
        migrations.AlterField(
            model_name="variedmenuitem",
            name="cooking_style",
            field=models.ForeignKey(
                db_column="cooking_style_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="jsquared_app.cookingstyle",
            ),
        ),
        migrations.AlterField(
            model_name="variedmenuitem",
            name="meat",
            field=models.ForeignKey(
                db_column="meat_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="jsquared_app.meatitem",
            ),
        ),
    ]
