# Generated by Django 5.1.6 on 2026-05-01 08:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsquared_app", "0003_create_render_superuser_retry"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="order_type",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cookingstyle",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cookingstyle",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fixedmenuitem",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedmenuitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="meatitem",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meatitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="variedmenuitem",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variedmenuitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("Staff", "Staff"),
                    ("Cashier", "Cashier"),
                    ("Manager", "Manager"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cookingstyle",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cookingstyle",
            name="meat_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cooking_styles",
                to="jsquared_app.meatitem",
            ),
        ),
        migrations.AlterField(
            model_name="meatitem",
            name="meat_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="meat_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="staff",
            field=models.ForeignKey(
                db_column="staff_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="jsquared_app.staff",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="fixed_item",
            field=models.ForeignKey(
                blank=True,
                db_column="fixed_item_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="jsquared_app.fixedmenuitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="varied_item",
            field=models.ForeignKey(
                blank=True,
                db_column="varied_item_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="jsquared_app.variedmenuitem",
            ),
        ),
        migrations.AlterField(
            model_name="priceinquiryrequest",
            name="meat",
            field=models.ForeignKey(
                db_column="meat_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="jsquared_app.meatitem",
            ),
        ),
        migrations.AlterField(
            model_name="priceinquiryrequest",
            name="requested_by",
            field=models.ForeignKey(
                db_column="requested_by",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="price_requests",
                to="jsquared_app.staff",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="suppliertransaction",
            name="payment_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Completed", "Completed")],
                default="Pending",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="suppliertransaction",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="jsquared_app.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="variedmenuitem",
            name="cooking_style",
            field=models.ForeignKey(
                db_column="cooking_style_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="jsquared_app.cookingstyle",
            ),
        ),
        migrations.AlterField(
            model_name="variedmenuitem",
            name="meat",
            field=models.ForeignKey(
                db_column="meat_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="jsquared_app.meatitem",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "purchase_item_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quantity", models.FloatField(default=0)),
                ("unit_price", models.FloatField(default=0)),
                (
                    "meat",
                    models.ForeignKey(
                        blank=True,
                        db_column="meat_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jsquared_app.meatitem",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        db_column="transaction_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_items",
                        to="jsquared_app.suppliertransaction",
                    ),
                ),
            ],
            options={
                "db_table": "PURCHASE_ITEM",
            },
        ),
    ]
