# Generated by Django 6.0.2 on 2026-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsquared_app", "0004_alter_order_staff_alter_orderitem_fixed_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="user",
        ),
        migrations.AlterField(
            model_name="staff",
            name="staff_email",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="staff_password",
            field=models.CharField(max_length=255),
        ),
    ]
