# Generated by Django 5.1.6 on 2026-05-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsquared_app", "0004_account_archived_at_account_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliertransaction",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
