# Generated by Django 4.2.28 on 2026-02-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsquared_app', '0005_remove_staff_user_alter_staff_staff_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meatitem',
            name='meat_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
