# Generated by Django 5.1.6 on 2026-03-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsquared_app", "0009_order_discount_percent_override"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="discount_percent_override",
            new_name="suki_discount_percent",
        ),
        migrations.AddField(
            model_name="order",
            name="pwd_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="senior_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="applied_discount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="diner_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="eligible_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                default="Unpaid",
                max_length=10,
            ),
        ),
    ]
