# Generated by Django 4.2.28 on 2026-03-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsquared_app', '0010_rename_discount_percent_override_order_suki_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingstyle',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='cookingstyle',
            name='meat_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooking_styles', to='jsquared_app.meatitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_quantity',
            field=models.FloatField(default=1),
        ),
    ]
