# Generated by Django 4.2.28 on 2026-04-15 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsquared_app', '0013_suppliertransaction_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jsquared_app.supplier'),
        ),
    ]
